/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Font;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import negocio.CtrlCliente;
import negocio.CtrlPedido;
import negocio.FabricaNegocios;
import objetos.Cliente;
import objetos.Pedido;
import objetos.Producto;

public class consultaPedido extends javax.swing.JFrame {

    private FabricaNegocios f = new FabricaNegocios();
    private CtrlPedido ctrlPedido = f.getCtrlPedido();
    private ArrayList<Pedido> listaPedidos = (ArrayList<Pedido>) ctrlPedido.consultar();
    private CtrlCliente ctrlCliente = f.getCtrlCliente();

    /**
     * Creates new form actualizarProducto
     */
    public consultaPedido() {
        initComponents();
        setLocationRelativeTo(this);
        actualizaTabla(listaPedidos);
    }

    /**
     * Método que actualiza la tabla.
     */
    public void actualizaTabla(ArrayList<Pedido> lista) {
        DefaultTableModel modelo = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };

        modelo.addColumn("Cliente");
        modelo.addColumn("Estado");
        modelo.addColumn("Fecha Entrega");
        modelo.addColumn("Fecha Pedido");
        modelo.addColumn("Fecha Precio Final");

        tablaConsulta.setModel(modelo);

        String[] datos = new String[5];
        if (lista != null) {
            for (Pedido a : lista) {
                datos[0] = String.valueOf(a.getCliente().getNombre());
                datos[1] = String.valueOf(a.getEstado());
                datos[2] = String.valueOf(a.getFechaEntregado());
                datos[3] = String.valueOf(a.getFechaPedido());
                datos[4] = String.valueOf(a.getPrecioFinal());
                modelo.addRow(datos);
            }
        }

        Font fuente = new Font("Microsoft JhengHei UI Light", Font.BOLD, 14);
        tablaConsulta.setFont(fuente);
        tablaConsulta.setModel(modelo);
    }

    /**
     * Método que regresa al producto que se desea eliminar.
     *
     * @return devuelve al producto seleccionado
     */
    public Producto seleccionado() {
        int seleccion = tablaConsulta.getSelectedRow();
        Cliente cliente = listaPedidos.get(seleccion).getCliente();
        String estado = listaPedidos.get(seleccion).getEstado();
        Date fechaE = listaPedidos.get(seleccion).getFechaEntregado();
        Date fechaP = listaPedidos.get(seleccion).getFechaPedido();
        Float precio = listaPedidos.get(seleccion).getPrecioFinal();

        Producto producto = new Producto();
        ctrlPedido.buscarNombre(cliente);

//        Pedido pedido = new Pedido(cliente, productos, fechaP, fechaE, estado, precio);
//                
//        producto.setId(listaPedidos.get(seleccion).getId());
//        producto.setNombre(listaPedidos.get(seleccion).getNombre());
//        producto.setDescripcion(listaPedidos.get(seleccion).getDescripcion());
//        producto.setPrecio(listaPedidos.get(seleccion).getPrecio());
//        producto.setStock(listaPedidos.get(seleccion).getStock());
        return producto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaConsulta.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Fecha", "Correo", "Telefono", "Domicilio"
            }
        ));
        tablaConsulta.setRequestFocusEnabled(false);
        tablaConsulta.getTableHeader().setReorderingAllowed(false);
        tablaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaConsultaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaConsulta);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 430, 300));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar.png"))); // NOI18N
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar2.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, -1));

        txtBusqueda.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txtBusqueda.setBorder(null);
        getContentPane().add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 200, 20));

        btnBuscar.setContentAreaFilled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 40, 35));

        btnBuscar1.setContentAreaFilled(false);
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 30, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaPedido.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        menuPedidos abrir = new menuPedidos();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tablaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaConsultaMouseClicked
        Producto cl = seleccionado();
        actualizarProducto c = new actualizarProducto(cl);
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_tablaConsultaMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        String busqueda = txtBusqueda.getText();
        List<Cliente> listCliente = ctrlCliente.buscarNombre(busqueda);
        ArrayList<Pedido> pedidosB = null;

        if (!listCliente.isEmpty()) {
            Cliente cliente = listCliente.get(0);
            pedidosB = (ArrayList<Pedido>) ctrlPedido.buscarNombre(cliente);
            if (pedidosB.isEmpty()) {
                actualizaTabla(listaPedidos);
            } else {
                actualizaTabla(pedidosB);
            }
        } else {
            actualizaTabla(pedidosB);
        }
    }//GEN-LAST:event_btnBuscar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaConsulta;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
