/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Font;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.CtrlCliente;
import negocio.CtrlPedido;
import negocio.CtrlProducto;
import negocio.FabricaNegocios;
import objetos.Cliente;
import objetos.Pedido;
import objetos.Producto;
import org.bson.types.ObjectId;

public class consultaPedido2 extends javax.swing.JFrame {

    private Pedido pedido;
    private FabricaNegocios f = new FabricaNegocios();
    private CtrlPedido ctrlPedido = f.getCtrlPedido();
    boolean confirmacion = false;
    
    private CtrlCliente ctrlCliente = f.getCtrlCliente();
    private ArrayList<Cliente> listaClientes = (ArrayList<Cliente>) ctrlCliente.consultar();
    private CtrlProducto ctrlProducto = f.getCtrlProducto();
    private ArrayList<Producto> listaProductos =(ArrayList<Producto>) ctrlProducto.consultar();
    private ArrayList<Producto> productosSeleccionados = new ArrayList<>();
    
    /**
     * Creates new form registrarCliente
     *
     * @param cliente
     */
    public consultaPedido2(Pedido pedido) {
        initComponents();
        setLocationRelativeTo(this);
        this.pedido = pedido;
        this.cargarClientes();
        this.cargarProductos();
        llenarCampos(pedido);
    }

    /**
     * Método que llena los campos del cliente que fue recibido
     *
     * @param cliente
     */
    public void llenarCampos(Pedido pedido) {
        txtFechaP.setText(pedido.getFechaPedido().toString());
        txtFechaE.setText(pedido.getFechaEntregado().toString());
        txtEstado.setText(pedido.getEstado());
        String cliente = pedido.getCliente().getNombre();
        for (int i = 0; i < listaClientes.size(); i++) {
            if (cliente.equals(cbCliente.getItemAt(i))) {
                cbCliente.setSelectedIndex(i);
                break;
            }
        }

        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };
        modelo.addColumn("Producto");
        modelo.addColumn("Precio");
        
        tableProductos.setModel(modelo);
        
        String[] a2 = new String[2];
        ArrayList<Producto> productos = pedido.getProductos();
        
        for (Producto pro : productos) {
            a2[0] = String.valueOf(pro.getNombre());
            a2[1] = String.valueOf(pro.getPrecio());
            modelo.addRow(a2);
        }
        Font fuente = new Font("Microsoft JhengHei UI Light", Font.BOLD, 14);
        tableProductos.setFont(fuente);
        tableProductos.setModel(modelo);

        txtTotal.setText(String.valueOf(pedido.getPrecioFinal()));
    }

    public void eliminar() {
        ctrlPedido.eliminar(pedido);
        JOptionPane.showMessageDialog(null, "PEDIDO ELIMINADO");
    }
    
    private void cargarClientes() {
        for (Cliente e : listaClientes) {
            this.cbCliente.addItem(e.getNombre());
        }
    }

    private void cargarProductos() {
       this.cbProducto.removeAllItems();
        //this.listaProductos = (ArrayList<Producto>) ctrlProducto.consultar();
        for (Producto p : listaProductos) {
            if (p.getStock() > 0) {
                String item = p.getNombre() + " | stock:" + p.getStock() + " | $" + p.getPrecio();
                this.cbProducto.addItem(item);
//                this.cbProducto.addItem(p.getNombre());
            }
        }
    }
    
    private void salir() {
        consultaEliminarPedido c = new consultaEliminarPedido();
        c.setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        txtFechaE = new javax.swing.JTextField();
        txtFechaP = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        cbCliente = new javax.swing.JComboBox<>();
        cbProducto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar.png"))); // NOI18N
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar2.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, -1, -1));

        txtTotal.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txtTotal.setBorder(null);
        txtTotal.setEnabled(false);
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 310, 23));

        txtFechaE.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txtFechaE.setBorder(null);
        txtFechaE.setEnabled(false);
        getContentPane().add(txtFechaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 140, 23));

        txtFechaP.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txtFechaP.setBorder(null);
        txtFechaP.setEnabled(false);
        getContentPane().add(txtFechaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 140, 25));

        txtEstado.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txtEstado.setBorder(null);
        txtEstado.setEnabled(false);
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 320, 25));

        txtCantidad.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        txtCantidad.setBorder(null);
        txtCantidad.setEnabled(false);
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 55, 25));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAtras.png"))); // NOI18N
        btnAgregar.setEnabled(false);
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 40, 40));

        cbCliente.setEnabled(false);
        getContentPane().add(cbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 273, 350, 30));

        cbProducto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cbProducto.setEnabled(false);
        getContentPane().add(cbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 130, 30));

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableProductos.setEnabled(false);
        jScrollPane1.setViewportView(tableProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 350, 90));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultaApedido.jpeg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.salir();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbProducto;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechaE;
    private javax.swing.JTextField txtFechaP;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
