/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.CtrlCliente;
import negocio.CtrlPedido;
import negocio.CtrlProducto;
import negocio.FabricaNegocios;
import objetos.Cliente;
import objetos.Pedido;
import objetos.Producto;

/**
 *
 * @author servando
 */
public class registrarPedido extends javax.swing.JFrame {

    private Date hoy;
    private ArrayList<Producto> productosSeleccionados = new ArrayList<>();
    private FabricaNegocios f = new FabricaNegocios();
    private CtrlPedido ctrlPedido = f.getCtrlPedido();
    private CtrlCliente ctrlCliente = f.getCtrlCliente();
    private ArrayList<Cliente> listaClientes = (ArrayList<Cliente>) ctrlCliente.consultar();
    private CtrlProducto ctrlProducto = f.getCtrlProducto();
    private ArrayList<Producto> listaProductos =(ArrayList<Producto>) ctrlProducto.consultar();
    //Este producto es el bueno
    //private ArrayList<Producto> listaProductosT= (ArrayList<Producto>) ctrlProducto.consultar();
    /**
     * Creates new form registrarPedido
     */
    public registrarPedido() {
        initComponents();
        hoy = new Date();
        //String fecha = (hoy.getDay() + 1) + "/" + (hoy.getMonth()+1) + "/" + hoy.getYear();
        String fecha = hoy.toString().replace("MTS", "");
        //String fecha = hoy.toString();
        txtFechaP.setText(String.valueOf(fecha));
        setLocationRelativeTo(this);
        this.cargarClientes();
        this.cargarProductos();
    }

    private void cargarClientes() {
        for (Cliente e : listaClientes) {
            this.cbCliente.addItem(e.getNombre());
        }
    }

    private void cargarProductos() {
       this.cbProducto.removeAllItems();
        //this.listaProductos = (ArrayList<Producto>) ctrlProducto.consultar();
        for (Producto p : listaProductos) {
            if (p.getStock() > 0) {
                String item = p.getNombre() + " | stock:" + p.getStock() + " | $" + p.getPrecio();
                this.cbProducto.addItem(item);
//                this.cbProducto.addItem(p.getNombre());
            }
        }
    }

    public boolean validar() {
        return false;
    }

    private void guardar() {

    }
    
    private void limpiar(){
        this.txtEstado.setText("");
        this.txtFechaE.setCalendar(null);
        this.cbCliente.setSelectedIndex(0);
        this.cbProducto.setSelectedIndex(0);
        this.txtTotal.setText("0.0");
        this.productosSeleccionados.clear();
        this.txtCantidad.setText("");
        DefaultTableModel modelo = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };
        this.tableProductos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFechaP = new javax.swing.JTextField();
        txtFechaE = new com.toedter.calendar.JDateChooser();
        txtEstado = new javax.swing.JTextField();
        cbCliente = new javax.swing.JComboBox<>();
        cbProducto = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFechaP.setEditable(false);
        txtFechaP.setBorder(null);
        getContentPane().add(txtFechaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 160, 25));

        txtFechaE.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaE.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaE.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        getContentPane().add(txtFechaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 210, 30));

        txtEstado.setBorder(null);
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 310, 25));

        getContentPane().add(cbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 300, -1));

        getContentPane().add(cbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 322, 110, 30));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAtras.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 40, 40));

        txtCantidad.setBorder(null);
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 50, 25));

        txtTotal.setEditable(false);
        txtTotal.setText("0.0");
        txtTotal.setBorder(null);
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 330, 20));

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 330, 90));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnGuardar.png"))); // NOI18N
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnGuardar2.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnGuardar2.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar.png"))); // NOI18N
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar2.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoRegistrarPedido.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Date fecha = txtFechaE.getDate();
        if(txtEstado.getText().isEmpty() || tableProductos.getModel().getRowCount()==0
                || txtTotal.getText().equalsIgnoreCase("0.0") || fecha == null){
            JOptionPane.showMessageDialog(null, "LlENE TODOS LOS CAMPOS");
            return;
        }
        
        //Actualiza el stock de los productos
        for(Producto pro: listaProductos){
            ctrlProducto.actualizar(pro);
        }
        listaProductos.clear();
        listaProductos = (ArrayList<Producto>) ctrlProducto.consultar();
        System.out.println(listaProductos.size());
        Cliente cliente = listaClientes.get(cbCliente.getSelectedIndex());
        String estado = txtEstado.getText().toUpperCase();
        float total = Float.parseFloat(txtTotal.getText());
        ctrlPedido.guardar(new Pedido(cliente,productosSeleccionados, hoy, fecha, estado,total));
        this.limpiar();
        JOptionPane.showMessageDialog(null, "Registro exitoso");
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        menuPedidos abrir = new menuPedidos();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!txtCantidad.getText().isEmpty()) {
            DefaultTableModel modelo = new DefaultTableModel() {

                @Override
                public boolean isCellEditable(int row, int colum) {
                    return false;
                }
            };
            modelo.addColumn("Producto");
            modelo.addColumn("Precio");

            int cantidad = Integer.parseInt(txtCantidad.getText());

            String[] a2 = new String[2];
            for (int i = 0; i < cantidad; i++) {
                productosSeleccionados.add(listaProductos.get(this.cbProducto.getSelectedIndex()));
            }
            
            //se elimina un stock del producto
            int stock = listaProductos.get(this.cbProducto.getSelectedIndex()).getStock();
            stock -= cantidad;
            listaProductos.get(this.cbProducto.getSelectedIndex()).setStock(stock);
            //Se actualiza el producto con el nuevo stock
            //ctrlProducto.actualizar(listaProductos.get(this.cbProducto.getSelectedIndex()));

            for (Producto pro : productosSeleccionados) {
                a2[0] = pro.getNombre();
                a2[1] = String.valueOf(pro.getPrecio());
                modelo.addRow(a2);
            }

            float total = Float.parseFloat(txtTotal.getText()) + (listaProductos.get(this.cbProducto.getSelectedIndex()).getPrecio() * cantidad);
            this.txtTotal.setText(String.valueOf(total));
            tableProductos.setModel(modelo);

            this.cargarProductos();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbProducto;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtEstado;
    private com.toedter.calendar.JDateChooser txtFechaE;
    private javax.swing.JTextField txtFechaP;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
